abdbankproject/abdbankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('banking.urls')),
    path('credentials/', include('credentials.urls')),
    path('loan/',include('loan.urls'))

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

abdbankproject/banking/urls.py
from django.urls import path

from banking import views

app_name = 'banking'

urlpatterns=[
    path('',views.index,name='index'),
    path('base/',views.base,name='base'),
    # path('contact/',views.contact,name='contact'),

]

abdbankproject/credentials/urls.py
from django.urls import path

from credentials import views

app_name = 'credentials'

urlpatterns=[
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout',views.logout,name='logout'),


]

abdbankproject/loan/urls.py
from django.urls import path

from loan import views

app_name = 'loan'

urlpatterns=[

    path('apply_loan/',views.loan,name='loan'),
    path('loan_application_accepted/',views.loan_application_accepted,name='loan_application_accepted'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),  # AJAX

]

abdbankproject/banking/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name=models.CharField(max_length=250,unique=True)


    def __str__(self):
        return self.name

class Branch(models.Model):
    name = models.CharField(max_length=250,unique=True)
    district =models.ForeignKey(District,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

abdbankproject/credentials/models.py
from django.db import models

# Create your models here.
class Material(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.name)

abdbankproject/loan/models.py
from django.db import models

from banking.models import District, Branch
from credentials.models import Material

# Create your models here.
gend=[
    ('Male','Male'),
    ('Female','Female'),
    ('Other','Other')
]

acc=[
    ('Current','Current'),
    ('Savings','Savings'),
]

lt=[
    ('Home_Loan','Home Loan'),
    ('Business_Loan','Business Loan'),
    ('Education_Loan','Education Loan'),
    ('Car_Loan','Car Loan')
]


class Loan(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    adress = models.TextField()
    email = models.EmailField()
    gender = models.CharField(max_length=100,choices=gend)
    phoneNum = models.CharField(max_length=10)
    DOB = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    materials = models.ManyToManyField(Material)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch,on_delete=models.SET_NULL, blank=True, null=True)
    account = models.CharField(max_length=100,choices=acc)
    loan_type = models.CharField(max_length=100,choices=lt)

    def __str__(self):
        return '{}'.format(self.email)

abdbankproject/credentials/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2')

abdbankproject/loan/forms.py
from django import forms

from banking.models import Branch
from credentials.models import Material
from loan.models import Loan


class DateInput(forms.DateInput):
    input_type = 'date'

class RadioSelect(forms.RadioSelect):
    input_type = 'radio'

class CheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    input_type = 'checkbox'



class LoanCreationForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ('first_name','last_name','email','gender','DOB','age','adress','phoneNum','district','branch','materials','account','loan_type')

        materials = forms.ModelMultipleChoiceField(
            queryset=Material.objects.all(),
        )
        widgets ={
            'DOB': DateInput(),
            'gender': RadioSelect(),
            'materials': CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

abdbankproject/banking/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def base(request):
    return render(request, 'base.html')

abdbankproject/credentials/views.py
from django.contrib import messages, auth
from django.shortcuts import render, redirect

from credentials.forms import CustomUserCreationForm


# Create your views here.
def register(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':

        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "Registered successfully")
            return redirect('credentials:login')
        else:
            form = CustomUserCreationForm()
    return render(request, 'register.html',{'form':form})


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
                auth.login(request,user)
                messages.info(request, "successfully logged in")
                return render(request,'apply.html')
        else:
                messages.info(request,"Invalid login credentials")
                return render(request,'login.html')
    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

abdbankproject/loan/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from banking.models import Branch
from loan.forms import LoanCreationForm


# Create your views here.
def loan(request):
    form = LoanCreationForm()
    if request.method=='POST':
        form = LoanCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "Application accepted")
            return redirect('loan:loan_application_accepted')
    return render(request,"loan.html",{'form':form})

def loan_application_accepted(request):
    return render(request,'loan_application_accepted.html')

def load_branches(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'branch_dropdown_list_options.html', {'branches': branches})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

abdbankproject/templates/apply.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Presento Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Presento
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/presento-bootstrap-corporate-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">
      <h1 class="logo me-auto"><a href="{% url 'banking:index' %}">ABD BANK<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'banking:index' %}">Home</a></li>
<!--          <li><a class="nav-link scrollto" href="#about">About</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Services</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Register</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Log In</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Log Out</a></li>-->
          <li class="dropdown"><a href="#"><span>All Branches</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for dist in link %}
                <li><a href="https://en.wikipedia.org/wiki/{{ dist.name }}">{{ dist.name }}</a></li>
              {% endfor %}

            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      {% if user.is_authenticated %}
            <a class="get-started-btn scrollto bg-white text-info"> Hello {{user.username}} </a>
            <a class="get-started-btn scrollto" href="{% url 'credentials:logout' %}">Logout</a>
            {% else %}
            <a class="get-started-btn scrollto" href="{% url 'credentials:register' %}">Register</a>
<!--            <li ><a class="getstarted scrollto" href="{% url 'credentials:login' %}">Login</a></li>-->
            {% endif %}

<!--      <a href="#about" class="get-started-btn scrollto">Register</a>-->
    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <div class="row">
        <div class="col-xl-6">
          <h1>Simply Amazing Policies</h1>
          <h2>A few words about us</h2>
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
      <div class="container" data-aos="zoom-in">

        <div class="clients-slider swiper">
          <div class="swiper-wrapper align-items-center">
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-1.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-2.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-3.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-4.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-5.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-6.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-7.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-8.png' %}" class="img-fluid" alt=""></div>
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Clients Section -->

  </main>


  <section>
     <div class="container">
        <div class="row gy-4 justify-content-center bg-white text-success p-4">

          <div class="col-lg-3">
            {% if messages %}
              <ul class="messages">
              {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
              {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>
     </div>
    <div>
      <center>
          <a href="{% url 'loan:loan' %}" class="get-started-btn scrollto">Apply</a>  for a <span>Loan</span>
      </center>
    </div>
  </section>


    <!-- ======= Footer ======= -->
  <footer id="footer">


    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>ABD BANK</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/presento-bootstrap-corporate-template/ -->
          Designed by <a href="https://bootstrapmade.com/">abd</a>
        </div>
      </div>
      <div class="social-links text-center text-md-end pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

abdbankproject/templates/branch_dropdown_list_options.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <option value="">---------</option>
    {% for branch in branches %}
    <option value="{{ branch.pk }}">{{ branch.name }}</option>
    {% endfor %}

</body>
</html>

abdbankproject/templates/loan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Presento Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Presento
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/presento-bootstrap-corporate-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">
      <h1 class="logo me-auto"><a href="{% url 'banking:index' %}">ABD BANK<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'banking:index' %}">Home</a></li>
<!--          <li><a class="nav-link scrollto" href="#about">About</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Services</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Register</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Log In</a></li>-->
<!--          <li><a class="nav-link scrollto" href="#services">Log Out</a></li>-->
          <li class="dropdown"><a href="#"><span>All Branches</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for dist in link %}
                <li><a href="https://en.wikipedia.org/wiki/{{ dist.name }}">{{ dist.name }}</a></li>
              {% endfor %}

            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      {% if user.is_authenticated %}
            <a class="get-started-btn scrollto bg-white text-info"> Hello {{user.username}} </a>
            <a class="get-started-btn scrollto" href="{% url 'credentials:logout' %}">Logout</a>
            {% else %}
            <a class="get-started-btn scrollto" href="{% url 'credentials:register' %}">Register</a>
<!--            <li ><a class="getstarted scrollto" href="{% url 'credentials:login' %}">Login</a></li>-->
            {% endif %}

<!--      <a href="#about" class="get-started-btn scrollto">Register</a>-->
    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <div class="row">
        <div class="col-xl-6">
          <h1>Simply Amazing Policies</h1>
          <h2>A few words about us</h2>
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
      <div class="container" data-aos="zoom-in">

        <div class="clients-slider swiper">
          <div class="swiper-wrapper align-items-center">
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-1.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-2.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-3.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-4.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-5.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-6.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-7.png' %}" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-8.png' %}" class="img-fluid" alt=""></div>
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Clients Section -->

  </main>

<!--loan form-->

  <div class="container">
    <div class="row">
        <div class="col bg-dark">
            <div class="p-3 text-center bg-dark">
                <h2 style="color:black;background:lightgray;">Loan Application</h2>

                <form method="post" id="loanForm"  enctype="multipart/form-data" data-branches-url="{% url 'loan:ajax_load_branches' %}" >
                {% csrf_token %}
                    <div class="col-md-8 d-inline-block align-stretch text-white bg-dark p-4" >

                      {{ form.as_p }}

                    </div>
                    <div class="col-md-8 d-inline-block align-stretch p-4 ">
                        <input type="submit" class="get-started-btn scrollto rounded border" value="Submit"><br><br>
                    </div>
                </form>

                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script>
                    $("#id_district").change(function () {
                        const url = $("#loanForm").attr("data-branches-url");  // get the url of the `load_cities` view
                        const districtId = $(this).val();  // get the selected country ID from the HTML input

                        $.ajax({                       // initialize an AJAX request
                            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                            data: {
                                'district_id': districtId       // add the country id to the GET parameters
                            },
                            success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                                /*

                                let html_data = '<option value="">---------</option>';
                                data.forEach(function (branch) {
                                    html_data += `<option value="${branch.id}">${branch.name}</option>`
                                });
                                console.log(html_data);
                                $("#id_branch").html(html_data);

                                */
                            }
                        });

                    });
                </script>
            </div>
        </div>
    </div>
  </div>

<!--end loan form-->

   <footer id="footer">


    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>ABD BANK</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/presento-bootstrap-corporate-template/ -->
          Designed by <a href="https://bootstrapmade.com/">abd</a>
        </div>
      </div>
      <div class="social-links text-center text-md-end pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>